# Generated by Django 5.2.2 on 2025-06-21 15:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Post', '0004_article_published'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='published',
        ),
    ]
