# Generated by Django 5.2.2 on 2025-06-21 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Post', '0006_article_is_published'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='is_published',
        ),
        migrations.AddField(
            model_name='article',
            name='text2',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
