# Generated by Django 5.2.2 on 2025-06-26 01:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Post', '0007_remove_article_is_published_article_text2'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='text2',
        ),
        migrations.AddField(
            model_name='article',
            name='is_published',
            field=models.BooleanField(default=False),
        ),
    ]
