# Generated by Django 5.2.2 on 2025-06-26 01:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Post', '0008_remove_article_text2_article_is_published'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='is_published',
        ),
    ]
