# Generated by Django 4.2.23 on 2025-07-01 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Post', '0010_article_published'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='published',
        ),
        migrations.AddField(
            model_name='article',
            name='test',
            field=models.TextField(blank=True),
        ),
    ]
