# Generated by Django 4.2.23 on 2025-07-01 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Post', '0011_remove_article_published_article_test'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='test',
        ),
        migrations.AddField(
            model_name='article',
            name='published',
            field=models.BooleanField(default=True),
        ),
    ]
