# Generated by Django 5.2.2 on 2025-06-18 19:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Login', '0002_profile_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='username',
        ),
    ]
