# Generated by Django 5.2.2 on 2025-06-18 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Login', '0003_remove_profile_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='username',
            field=models.CharField(default=1122, max_length=50, unique=True),
            preserve_default=False,
        ),
    ]
