# Generated by Django 5.2.2 on 2025-06-19 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Login', '0005_alter_profile_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='userCode',
            field=models.CharField(max_length=12, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='username',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
