# Generated by Django 5.2.2 on 2025-06-19 16:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Login', '0006_alter_profile_usercode_alter_profile_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='userCode',
        ),
    ]
