# Generated by Django 5.2.2 on 2025-06-19 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Login', '0007_remove_profile_usercode'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='userCode',
            field=models.CharField(max_length=12, null=True),
        ),
    ]
